In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [9]:
import os

print(os.listdir('/content'))

['.config', 'archive (1).zip', 'sample_data']

In [15]:
import zipfile
import pandas as pd

with zipfile.ZipFile('/content/archive (1).zip', 'r') as zip_ref:
    zip_ref.extract('Reviews.csv', '/content/')

In [16]:
df = pd.read_csv('/content/Reviews.csv', nrows=50000)

print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (50000, 10)

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...

In [17]:
light_reviews = df[df["Text"].str.contains(r"\blight\b",
                                           case=False,
                                           na=False)]

print("Number of reviews containing 'light':", len(light_reviews))
light_reviews["Text"].head(20)

Number of reviews containing 'light': 1415

2      This is a confection that has been around a fe...
238    A very delicate green tea with a smooth light ...
269    This is a delicious sugar. It has a pretty lig...
396    Arrowhead Mills Buttermilk Pancake mix is my f...
404    A good tasting light chip that has some value ...
462    Kettle Chips flavors can be hit or miss.  Some...
466    I'm addicted to salty and tangy flavors, so wh...
467    These Honey Dijon chips bring a terrific balan...
486    Just got this order and it is ok. A bit light ...
556    DEfintely not as tasty as the Madhouse Munchie...
571    With Kettle Chips, you really have to be caref...
574    I'm addicted to salty and tangy flavors, so wh...
602    As an Oregonian, I make a point of sharing the...
603    I'm addicted to salty and tangy flavors, so wh...
635    I want to like Kettle because they contain no ...
649    So I got this and tasted it strait out of the ...
653    If you want to find a good flavor substitute f...
712    My husband (who, being Mexican, is very picky ...
720    I received this chips in a gift basket and abs...
721    These chips are truly amazing. They have it al...
Name: Text, dtype: object

In [24]:
for i, review in enumerate(light_reviews["Text"].head(30)):
    print(f"\nReview {i+1}")
    print(review)

Review 1
This is a confection that has been around a few centuries.  It is a light, pillowy citrus gelatin with nuts - in this case Filberts. And it is cut into tiny squares and then liberally coated with powdered sugar.  And it is a tiny mouthful of heaven.  Not too chewy, and very flavorful.  I highly recommend this yummy treat.  If you are familiar with the story of C.S. Lewis' "The Lion, The Witch, and The Wardrobe" - this is the treat that seduces Edmund into selling out his Brother and Sisters to the Witch.

Review 2
A very delicate green tea with a smooth light taste and an subtle floral tones and no bitter aftertaste.<br /><br />In the 20+ years we have been drinking Ahmad teas not even once have we been disappointed. The superb quality of Ahmad teas has remained consistent throughout the years.<br /><br />I am so happy to find Ahmad teas available here (thanks Amazon!) because only a few stores carry it in my area and they are quite a few miles away. The current deal for the pack of 6 is superb (much cheaper than I can find locally).<br /><br />This is a great tasting tea, which I am happy to recommend.

Review 3
This is a delicious sugar. It has a pretty light brown color and delicious aroma. But the granules are quite big, however -- bigger than plain refined sugar. This makes is difficult to cream butter and sugar together. But if you use it in a recipe where you will melt the sugar first before baking it, or if you use it to brew beer and plan to boil it to melt it, it is a great product. It would be the perfect sugar if only the granules were a bit finer.

Review 4
Arrowhead Mills Buttermilk Pancake mix is my favorite mix.  It tastes great, cooks up light and fluffy and is super easy to make.  Although it can be made using water, I think it's better made with milk.  I love it with pure organic maple syrup.

Review 5
A good tasting light chip that has some value in nutrition.  Everyone get the munchies....is this is a good alternative to eating potato chips!

Review 6
Kettle Chips flavors can be hit or miss.  Some of their flavors are terrible.  But this is very simple and delicious.  Probably one of their best flavors.<br /><br />Pros: Thick, crunchy potato chips with light salt that doesn't compromise on taste, eco-friendly business that isn't just giving us lip service<br /><br />Cons: The occasional burnt chip and the bag is a pain to open.  They have a tab that you can pull down but most of the time I end up tearing down the entire side of the bag.  Use scissors instead.

Review 7
I'm addicted to salty and tangy flavors, so when I opened my first bag of Sea Salt & Vinegar Kettle Brand chips I knew I had a perfect complement to my vegetable trays of cucumber, carrot, celery and cherry tomatoes. Skip the dip; balance the tangy chips by alternating bites of raw vegetable.<br /><br />As an Oregonian, I'm proud to share these delectable snacks with friends, especially those living outside our state and who haven't experienced gourmet chips. I tell them Kettle Brand does for potato chips what microbrews did for beer.<br /><br />Kettle Brand potato chips are unmistakable--a light gold color, rich flavor and amazing crunch. Kettle Brand chips are also a healthier snacking option than the major chip brands. Kettle Brand chips don't have trans fats, MSG or artificial flavors and colorings. The company also has a line of organic potato chips and all of their products are certified Kosher.<br /><br />I also recommend <a href="http://www.amazon.com/gp/product/B000G6MBV4">Kettle Chips Honey Dijon</a> and <a href="http://www.amazon.com/gp/product/B000G6Q4GM">Kettle Chips Spicy Thai</a>.<br /><br />Annette Solomon, a reporter for the Salem Statesman Journal recently noted that a glass of wine goes nicely with these chips. Solomon wrote, "...you could be missing out on a wonderful pairing. These chips are spicy, so you would want to select a semi-sweet white wine. Also, a moderate amount of acid will subdue the strong flavors of ginger, lime, garlic and cilantro without over-powering them. Classically, a German-style Riesling fits these parameters perfectly."

Review 8
These Honey Dijon chips bring a terrific balance of salty, tangy, sweet and crunchy. Other brands I've tried use too much mustard flavor, which overpowers the Honey Dijon pairing.<br /><br />These chips make a great side dish on a BBQ plate with baked beans, coleslaw or potato salad and grilled meat. Naturally, they also go down great with beer.<br /><br />As an Oregonian, I'm proud to share these delectable snacks with friends, especially those living outside our state and who haven't experienced gourmet chips. I tell them Kettle Brand does for potato chips what microbrews did for beer.<br /><br />Kettle Brand potato chips are unmistakable--a light gold color, rich flavor and amazing crunch. Kettle Brand chips are also a healthier snacking option than the major chip brands. Kettle Brand chips don't have trans fats, MSG or artificial flavors and colorings. The company also has a line of organic potato chips and all of their products are certified Kosher.<br /><br />I also recommend these other Kettle Chips flavors: <a href="http://www.amazon.com/gp/product/B000G6MBUA">Kettle Chips Sea Salt & Vinegar</a> and <a href="http://www.amazon.com/gp/product/B000G6Q4GM">Kettle Chips Spicy Thai</a>.<br /><br />Annette Solomon, a reporter for the Salem Statesman Journal recently noted that a glass of wine goes nicely with these chips. Solomon wrote, "...you could be missing out on a wonderful pairing. These chips are spicy, so you would want to select a semi-sweet white wine. Also, a moderate amount of acid will subdue the strong flavors of ginger, lime, garlic and cilantro without over-powering them. Classically, a German-style Riesling fits these parameters perfectly."

Review 9
Just got this order and it is ok. A bit light on the cheddar flavoring and herb taste eludes me, if it is there.

Review 10
DEfintely not as tasty as the Madhouse Munchies which are my family's favorite. Kettle's are dark/burnt,more broken bits, taste greasy-oily and not the light crunch. Oh well.

Review 11
With Kettle Chips, you really have to be careful.  Some of their flavors are nauseating.  With that said, they DO make fantastic plain chips.  Thick cuts of potato, fried to a dark golden brown.  They are crunchy and lightly salted with sea salt.  I can't recommend these chips enough.  You won't regret it.<br /><br />Some people say they are burnt but they aren't.  From their website: "Take a quick look and you'll see an immediate difference: Kettle Brand® Potato Chips are a beautiful tawny gold. During cooking, the natural sugars of our select potatoes caramelize, creating chips from light gold to a deep amber.  The results are flavors as deep and rich as the colors, and an artisanal display in every bag"<br /><br />Some have also said that these chips are oily, which is true.  But they explain that on their website: "At Kettle Foods we exclusively use expeller pressed high monounsaturated sunflower and/or safflower oil to make Kettle Brand®  products. Both of these oils are naturally free of trans fatty acids and are not hydrogenated in any way. We have taken the extra step of sending our products to independent third party labs to test for the presence of trans fats and results indicate we are "trans fat free" meaning none were detected. You will see zero trans fats listed on our packaging."  That oiliness is natural and happens when quality oil is being used.<br /><br />You will not find chips with such a natural potato flavor.  I'm also a fan of their unsalted potato chips.  For those of us watching our salt intake, the unsalted chips is the best you can get.  Period.

Review 12
I'm addicted to salty and tangy flavors, so when I opened my first bag of Sea Salt & Vinegar Kettle Brand chips I knew I had a perfect complement to my vegetable trays of cucumber, carrot, celery and cherry tomatoes. Skip the dip; balance the tangy chips by alternating bites of raw vegetable.<br /><br />As an Oregonian, I'm proud to share these delectable snacks with friends, especially those living outside our state and who haven't experienced gourmet chips. I tell them Kettle Brand does for potato chips what microbrews did for beer.<br /><br />Kettle Brand potato chips are unmistakable--a light gold color, rich flavor and amazing crunch. Kettle Brand chips are also a healthier snacking option than the major chip brands. Kettle Brand chips don't have trans fats, MSG or artificial flavors and colorings. The company also has a line of organic potato chips and all of their products are certified Kosher.<br /><br />I also recommend <a href="http://www.amazon.com/gp/product/B000G6MBV4">Kettle Chips Honey Dijon</a> and <a href="http://www.amazon.com/gp/product/B000G6Q4GM">Kettle Chips Spicy Thai</a>.<br /><br />Annette Solomon, a reporter for the Salem Statesman Journal recently noted that a glass of wine goes nicely with these chips. Solomon wrote, "...you could be missing out on a wonderful pairing. These chips are spicy, so you would want to select a semi-sweet white wine. Also, a moderate amount of acid will subdue the strong flavors of ginger, lime, garlic and cilantro without over-powering them. Classically, a German-style Riesling fits these parameters perfectly."

Review 13
As an Oregonian, I make a point of sharing these Oregon-made snacks with friends who visit the state. I tell them the Kettle Brand does for potato chips what microbrew does for beer.<br /><br />Kettle Brand potato chips are unmistakable--a light gold color, rich flavor and amazing crunch. Kettle Brand chips are also a healthier snacking option than the major chip brands. Kettle Brand chips don't have trans fats, MSG or artificial flavors and colorings. The company also has a line of organic potato chips and all of their products are certified Kosher.<br /><br />Annette Solomon, a reporter for the Salem Statesman Journal noted that a glass of wine goes nicely with Spicy Thai chips. Solomon wrote, "...you could be missing out on a wonderful pairing. These chips are spicy, so you would want to select a semi-sweet white wine. Also, a moderate amount of acid will subdue the strong flavors of ginger, lime, garlic and cilantro without over-powering them. Classically, a German-style Riesling fits these parameters perfectly."<br /><br />I also recommend <a href="http://www.amazon.com/gp/product/B000G6MBV4">Kettle Chips Honey Dijon</a> and <a href="http://www.amazon.com/gp/product/B000G6MBUA">Kettle Chips Sea Salt & Vinegar</a>.<br /><br />The Honey Dijon chips bring a terrific balance of salty, tangy, sweet and crunchy. Other brands I've tried use too much mustard flavor, which overpowers the Honey Dijon pairing. The Honey Dijon chips make a great side dish on a BBQ plate with baked beans, coleslaw or potato salad and grilled meat. Naturally, they also go down great with beer.<br /><br />The Sea Salt & Vinegar chips are a perfect complement to vegetable trays of cucumber, carrot, celery and cherry tomatoes. Skip the dip; balance the tangy chips by alternating bites of raw vegetable.<br /><br />In summary, I highly recommend Kettle Brand chips, a great buy on Amazon.com.

Review 14
I'm addicted to salty and tangy flavors, so when I opened my first bag of Sea Salt & Vinegar Kettle Brand chips I knew I had a perfect complement to my vegetable trays of cucumber, carrot, celery and cherry tomatoes. Skip the dip; balance the tangy chips by alternating bites of raw vegetable.<br /><br />As an Oregonian, I'm proud to share these delectable snacks with friends, especially those living outside our state and who haven't experienced gourmet chips. I tell them Kettle Brand does for potato chips what microbrews did for beer.<br /><br />Kettle Brand potato chips are unmistakable--a light gold color, rich flavor and amazing crunch. Kettle Brand chips are also a healthier snacking option than the major chip brands. Kettle Brand chips don't have trans fats, MSG or artificial flavors and colorings. The company also has a line of organic potato chips and all of their products are certified Kosher.<br /><br />I also recommend <a href="http://www.amazon.com/gp/product/B000G6MBV4">Kettle Chips Honey Dijon</a> and <a href="http://www.amazon.com/gp/product/B000G6Q4GM">Kettle Chips Spicy Thai</a>.<br /><br />Annette Solomon, a reporter for the Salem Statesman Journal recently noted that a glass of wine goes nicely with these chips. Solomon wrote, "...you could be missing out on a wonderful pairing. These chips are spicy, so you would want to select a semi-sweet white wine. Also, a moderate amount of acid will subdue the strong flavors of ginger, lime, garlic and cilantro without over-powering them. Classically, a German-style Riesling fits these parameters perfectly."

Review 15
I want to like Kettle because they contain no corn oil or soybean oil (which are both GMO, and also my kids are allergic to corn and soy), but darnit, these things bite back! On the plus side, the sharpness of them may keep you from mindlessly enjoying too many. On the minus side, a mouthful of cuts and scratches is not worth it. Do they have to be SO hard and crunchy? What's wrong with simply light and crispy? I vastly prefer Lay's texture, but suffer with Kettle due to the absense of GMOs and corn/soy. I wish they'd come out with something less harsh on the mouth, though.

Review 16
So I got this and tasted it strait out of the bottle, it tasted like smoky flavored milk - YUCK! I was depressed I was stuck with 4 bottles of this.  It sat on my shelf and I forgot about it. Last weekend I tasted a Zevia cream soda and was not pleased with the flavor, it tasted weird and smokey like the LorAnn oil I had gotten.  I tried to doctor up the soda with a little SF Vanilla Torani syrup and a tablespoon of heavy cream - IT TASTED AMAZING!!!  The odd smokiness was gone and it had a wonderful rich mouthfeel.<br /><br />So I wanted to see if this would help the LorAnn oil too.  I put a cup of whipping cream in a bowl and added a teaspoon of vanilla and tasted it, it tasted fine.  Then I added ONE DROP of the oil, it is very strong, and stirred it in - IT TASTED SO MUCH BETTER!  I whipped it up and put it on fruit and it was such a treat.<br /><br />Now I will always whip a drop of it with vanilla into desserts and whip cream.  It was such a happy accident to find out how to use it.  When added to vanilla it really adds a new depth of flavor and tastes so different than just out of the bottle or on its own in cream.<br /><br />It is VERY potent so only use a drop and increase after tasting, if you add too much it will ruin the recipe so use a light touch.

Review 17
If you want to find a good flavor substitute for maple syrup, barley malt, or brown rice syrup, this will do nicely. I use Madhava's agave nectar in my baked goods all the time, and am always pleased with the results. At the time I'm writing this, Amazon was out of stock as a vendor. However, when it was in stock, it was priced well for the 2-pack.<br /><br />Other than baking, I've used it to top waffles, pancakes, and in small doses (1/2 teaspoon) added it to oatmeal. A little goes a long way.<br /><br />Using agave nectar: Use 1/3 to 1/2 less agave nectar than you would another sweetener (depending on your taste and the recipe. Recipes with dried fruit need much less), cut the heat in the oven by 25 degrees F; if there is oil in the recipe, cut it by 1/3 (alternately, use a tablespoon or two of sifted coconut flour to absorb more of the liquid -- just don't use too much or your recipe will be dry). Additionally, when baking, make sure to mix it with the wet ingredients prior to adding it to the dry. Most bakers might already know this, but remember to read recipes first because sugar is typically added with dry ingredients (unless beaten with butter first).<br /><br />Agave nectar does not crystalize like other sugars do, so you won't be able to substitute it for corn syrup in making hard candy. However, I highly recommend it for baking. It makes everything moister.<br /><br />If you are looking for less caramel flavor, you'll need to use the light version of this product (equally good in all applications).

Review 18
My husband (who, being Mexican, is very picky about his tortilla chips) and I absolutely love these!  The texture is light and crispy, rather than thick and crunchy. He actually usually prefers a very hearty, cruncy chip (Like El Ranchero), but the flavor of these is so fantastic that we're both thilled with them. The bean, rice and corn base makes them incredibly flavorful, and they have a touch of onion and garlic in addition to that. We go through an embarrassing amount of them.  I never, ever like plain chips, but these I can eat without anything else, although they're particularly amazing with a fresh salsa.  I highly recommend these!

Review 19
I received this chips in a gift basket and absolutely loved them. I searched high and low, but was unable to find them until I saw them here. I immediately ordered a case. These chips are light, crispy, flavorful, and good for you. I love them with dip, in chili, or just plain. Once you try them, you'll be hooked!

Review 20
These chips are truly amazing. They have it all. They're light, crisp, great tasting, nice texture, AND they're all natural... AND low in fat and sodium! Need I say more? I recently bought a bag of them at a regular grocery store, and couldn't belive my taste buds. That's why I excited why I saw them here on Amazon, and decided to buy a case!

Review 21
I love Cherrybrook Kitchen and have tried almost all of their products.  I was excited to try the Ready to Spread frosting, as I do not usually keep the needed ingredients on hand for their box frosting.  I am not a picky eater, especially if the item contains sugar... but this was horrible!  The consistency is absolutely nothing like regular canned frosting.  It is not light and fluffy.  It is very gooey.  I cannot even imagine trying to spread it on a cake - it would rip it to pieces because it is so thick and gooey.  I did not even try it on a cake, because the taste and texture were so off-putting.  Seriously, do not waste your money!

Review 22
This is pretty good regular style soy sauce.  But it is not super-wonderful-better than any other good quality soy sauce you can buy in an Asian market.  The main value is as a unique gift.<br />  In the Japanese soy sauce world, there are 4 types: regular, mild (usukuchi), for raw fish (sashimi) and light colored.  Bluegrass soy sauce is regular style.  Compared to Kikoman (a good commercial brand that is widely available) Bluegrass starts saltier, is flat in the middle, then ends with a complex & interesting flavor.  Kikoman is less salty initially and has a round, full flavor in the middle.  Doesn't have the complex ending flavors.  For me, the initial saltiness of Bluegrass is a minus and Kikoman's full middle flavor is a plus.  I prefere Kikoman, especially for dipping sushi where the flavor is more direct.  But I lived in Japan for many years and am used to the standard Japanese flavor.  I haven't tried Bluegrass blended in other food as a background flavor, which is how soy sauce is usually used.<br />  Bluegrass is a perfectly good soy sauce.  Each brand has a different flavor and everyone has their favorite.  If you want a unique Kentucky gift for an Asian friend, this is different than the standard bottle of Bourbon or box of chocolate.

Review 23

In [20]:
sentences = [
    "This olive oil is wonderful and very light on the stomach.",
    "The packaging was broken and let too much light inside the box.",
    "I prefer this brand because it is a light and healthy snack."
]

In [21]:
vectorizer = CountVectorizer()

doc_term_matrix = vectorizer.fit_transform(sentences)

dense_matrix = doc_term_matrix.toarray()

print("Dense Matrix:")
print(dense_matrix)

Dense Matrix:
[[1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]
 [1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]]

In [22]:
vec_1 = dense_matrix[0]
vec_2 = dense_matrix[1]
vec_3 = dense_matrix[2]

print("Vector 1:", vec_1)
print("Vector 2:", vec_2)
print("Vector 3:", vec_3)

Vector 1: [1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]
Vector 2: [1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]
Vector 3: [1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]

In [23]:
similarity_1_2 = np.dot(vec_1, vec_2)
similarity_1_3 = np.dot(vec_1, vec_3)

print("\nSimilarity Scores")
print("------------------")
print("Sentence 1 vs Sentence 2:", similarity_1_2)
print("Sentence 1 vs Sentence 3:", similarity_1_3)

Similarity Scores
------------------
Sentence 1 vs Sentence 2: 4
Sentence 1 vs Sentence 3: 4